### ISSUE TITLE
Make Rule of Merging Pull Request

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#12]
We need to make a rule of merging a pull request.
I think a simple rule is sufficient for this time.
@sergefdrv, @Naoya-Horiguchi, please give me your comments and suggestions.

- A pull request must be reviewed by one of the nec-blockchain members (@sergefdrv, @Naoya-Horiguchi and @ynamiki).
- The reviewer merges the request if it is fine.
- If the contributor (i.e. a creator of a Pull Request) is a member of nec-blockchain, the request must be reviewed and is merged by another member.

**Comment by sergefdrv** [comment]
I am absolutely fine with these rules :+1:

**Comment by nhoriguchi** [comment]
+1

**Comment by ynamiki** [comment]
Thanks, let's start with the rules.
If you are inconvenienced in practice, please create an issue to update the rule.

**Comment by sergefdrv** [comment]
I'm wondering how to handle updates to pull request based on review comments. I'm not really happy that GitHub in contrast to GitLab doesn't allow to see different versions of rebased and force-pushed commit series :slightly_frowning_face: It looks like the expected way to address review comments is to add additional commits on top. I believe this will make history cluttered and less useful. I was used to a more old-fashion workflow:

- Send a patch series to the mailing list, with a cover letter explaining the whole series. This is analogous to submitting a pull request in GutHub
- Collect review comments and discuss.
- Overwrite the commits that need to be changed. Drop commits that do not make sense. Create new commits only if that makes the series to a more compelling story.
- Send revised commit sequence as another patch series to the mailing list, labelling it with version number, like v2, v3 etc. And repeat the review-revise-resend as necessary.
- When the series is good enough to merge, it gets applied to the master branch, with no merge commit.

What I liked in that workflow is that it produced a clean readable history of changes applied to the mater branch. This history could be referred to later to easily find the meaningful commit that made a certain change, e.g. using `git blame`. I also liked to see a patch/commit series as a compelling story telling how the proposed bigger change is achieved with smaller, conceivable steps.

I'm afraid that addressing review comments in separate commits would introduce too much noise in the history and make it less usable. On the other hand, rewriting commits with `git rebase` and `git push --force` on a MR in GutHub seem to hide reviewer comments on the older versions of the commits and the commits might be shown in a weird order. 

It could help to create a new pull request for each revision of the commit series, similar to sending another version of a patch series. The easiest solution to fix the order GitHub shows the commits is to use `git rebase --ignore-date` if commit order was changed from original.

What do you think?

PS. @Naoya-Horiguchi seem to have appreciated the way the last series was split https://github.com/nec-blockchain/minbft/pull/14#issuecomment-408305157:

> patch descriptions are nicely written and I felt easy to understand what you try to do

which suggests that keeping the history clean might make actually sense :slightly_smiling_face:

**Comment by ynamiki** [comment]
Making rule that create a new pull request for each revision is no problem for me.

I also like "clean" (e.g. no separate commits for addressing review comments) commit history (but my ideal way is slightly different from yours: use a feature branch and merge with `git merge --no-ff` after review). But I have no good idea to bring the way to GitHub Pull Request straightforwardly.

**Comment by sergefdrv** [comment]
Good that we share the same attitude towards keeping history clean. Frankly, I don't have a strong preference between fully linear history and the approach with `git merge --no-ff`. Although, a linear history looks nice, the benefit of the latter approach is that if any intermediary commit in the pull request that might break build, wouldn't break `git bisect` completely. That is a useful property, since we don't run CI for every commit.

A way to achieve the ability to keep track of difference from revision to revision of a pull request might be like this:

- Each pull request should be made using a branch (e.g. `some-feature`) in a fork of the repository. After the pull request is submitted, the branch commits shouldn't be changed (no force-push).
- After review comments are collected, they should be addressed preferably by directly changing the corresponding commits (by doing rebase). 
- The updated revision of proposed changes is pushed to the fork of the repository in a new branch named with a prefix indicating the revision number, e.g. `some-feature-v2`, `some-feature-v3` etc.
- A new pull request should be submitted using that branch. The pull request should have revision indicated in the title, like "Add some feature v2". It should also reference the previous pull request, and preferably have a short summary of changes made since the previous revision.

When reviewing revision after revision, those branches can be used to [compare](https://help.github.com/articles/comparing-commits-across-time/) and see the actual delta between revisions.

**Comment by sergefdrv** [comment]
We might also want to summarize the rules in https://github.com/nec-blockchain/minbft#contributing or in separate file as suggested at https://help.github.com/articles/setting-guidelines-for-repository-contributors/.

**Comment by ynamiki** [comment]
@sergefdrv Thanks a lot for compiling the procedure. It is good to me.
@Naoya-Horiguchi What do you think?

**Comment by nhoriguchi** [comment]
I totally agree on how we prepare a branch for pull-request. I'll follow it.

**Comment by sergefdrv** [comment]
What do you think about possible actions provided by "Merge button"? https://help.github.com/articles/about-merge-methods-on-github/

**Comment by ynamiki** [comment]
@sergefdrv I like the default Merge pull request option. Other options, squashing and rebasing change the well-arranged commit history (including the hash) in a pull request.

**Comment by sergefdrv** [comment]
@ynamiki Sorry, I used "Rebase and merge" to merge #14. I mistakenly thought it will rebase the topic branch on top of the the master and then merge with `--no-ff` option. I confused it with GitLab's "Merge commit with semi-linear history" strategy which is my personal favourite... Should we then disable other options in section "Merge button" of the project settings?

**Comment by ynamiki** [comment]
@sergefdrv No problem. I have disabled squashing and rebasing in the repository settings.
https://help.github.com/articles/about-merge-methods-on-github/

**Comment by ynamiki** [comment]
Shall I close this issue and create a new issue for https://github.com/hyperledger-labs/minbft/issues/12#issuecomment-408793668?

**Comment by nhoriguchi** [comment]
@ynamiki creating a new issue makes sense to me. GitHub seems not to support "subtask" feature (surprising to me), but if we have it would be suitable for this case.

**Comment by sergefdrv** [comment]
> Shall I close this issue and create a new issue for #12 (comment)?

@ynamiki As you prefer. We actually have a rule. Documenting the rule might be considered a separate issue.

> GitHub seems not to support "subtask" feature

Issues can be "linked" instead by referring to one issue in a comment to another.

**Comment by ynamiki** [comment]
Created the separate issue for the documenting.
