### ISSUE TITLE
Create a project board and milestones

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#171]
To visualize what we are doing and when we plan to release, I would like to create a project board ("kanban").

Specifically, I am thinking of:
- Creating a project board with columns "To do", "In progress", "Review in progress", "Reviewer approved", and "Done" (these are provided by a GitHub's template).
- Creating milestones with a certain period (Q1 2020, Q2 2020, ..., or Early 2020, Mid 2020, Late 2020, ..., etc.).

I think our workflow do not change so much:
1. Create an issue and **set a milestone**.
2. When you start the task, **move a card** that represents the issue in a project board to the column "In progress".

Note that almost all status updates of a card in the project board will be done [automatically](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-project-boards).

@sergefdrv @Naoya-Horiguchi Your comments and suggestions are welcome. Is it overkill for our project?

**Comment by ynamiki** [comment]
Try a project board:
https://github.com/hyperledger-labs/minbft/projects/1

**Comment by sergefdrv** [comment]
Thank you, let's give it a try! I guess the first step would be to add "To Do" label to the issues that we plan to address in the near future. 

> Creating milestones with a certain period

We could alternatively create milestones based on big pieces of work rather than time-based, e.g. "View change implemented" or "Checkpoints implemented". What do you think?

**Comment by nhoriguchi** [comment]
I'm fine to try the project page, too. Maybe we need start with creating all possible tasks to GitHub issues. It's desirable to make the tasks broken down to properly sized ones (to make schedules predictable). And then, we can think of which set of issues should be solved for next milestone.

> We could alternatively create milestones based on big pieces of work rather than time-based, e.g. "View change implemented" or "Checkpoints implemented". What do you think?

I simply prefer version-based milestone (like "v0.1"), because feature-based one might give an impression that issues not related to the feature might not be developed/accepted until the milestone is released. Maybe there might be no/little difference, but version-based one might be more flexible for potential change of plan.

**Comment by ynamiki** [comment]
@sergefdrv @Naoya-Horiguchi Thanks for your comments! I'm fine with non-time-based milestone but I wanted to see rough schedule of each item. So how about doing it the following way.

- Create an issue for each development item/task.
- Create milestones with numerical versions (e.g. v0.1.0, v0.2.0, ...) with [Semantic Versioning](https://semver.org/) style.
  - A test milestone for [v0.1.0](https://github.com/hyperledger-labs/minbft/milestone/1)
- Discuss main features and expected release date for a milestone.
  - A test issue for [v0.1.0](#172).
- For issues, set assignee and a milestone based on the discussion then start the development.

I have updated the setting in Project Board Automation a newly added issue not to be placed the column "To do".

**Comment by ynamiki** [comment]
I have created some milestones and issues that are linked to each milestone.
Let's start and feel free to post your comments about any improvements of the way.

https://github.com/hyperledger-labs/minbft/milestones
https://github.com/hyperledger-labs/minbft/projects/1
