### ISSUE TITLE
Code review responsibilities

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#183]
As we discussed in #12, pull requests must be reviewed by one of the [minbft-committers](https://github.com/orgs/hyperledger-labs/teams/minbft-committers) members (former [nec-blockchain](https://github.com/nec-blockchain) members). So far I used to request review from both @ynamiki and @Naoya-Horiguchi for my pull requests and wait for both to approve before merging. I was wondering if this might be too much overhead and you would like to somehow split review responsibilities?

**Comment by nhoriguchi** [comment]
> I was wondering if this might be too much overhead and you would like to somehow split review responsibilities?

I had the same impression, and I felt sorry when I was blocking the process... Splitting review responsibility could be one solution so I'm OK to try it, but it's a little unclear to me how to split the subsystem for each developer.

Maybe another action we could take is to add the policy that a PR should be merged when it get (exactly) one approval with some (24h for example) lead time for the second reviewer.

**Comment by ynamiki** [comment]
@sergefdrv Thank you for your suggestion.

I'm fine with that; actually I have thought I should try to update the review process for faster development without my slow response.

> Maybe another action we could take is to add the policy that a PR should be merged when it get (exactly) one approval with some (24h for example) lead time for the second reviewer.

@Naoya-Horiguchi's suggestion looks good for me because we don't have clear assignation now (to be honest, @Naoya-Horiguchi takes almost all of the role). How about trying the way with 24h for the lead time tentatively? In any case, I will leave a comment in a PR if I need a long time for a review not to block the process.

**Comment by sergefdrv** [comment]
Let me share with you some thoughts. I think the following aspects matter the most.

**Whom to request review from?** So far the pace of contribution looks moderate, and all maintainers seem to care about most of the changes. Nevertheless, we could make it a bit more convenient and [set up code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners), even if it would be as simple as making all maintainers default owners for everything in the repo. It could also make sense to expect former contributors to the modified code making more thorough review.

**How long to wait for feedback?** Maybe 24 hours is a bit short notice. I would suggest to give the assigned reviewers a couple of working days for giving their feedback or explicitly asking for more time. In the latter case, the author might remind the delayed reviewer after a week and give another week.

**How to merge?** Currently, each request seems to only require no negative and at least one positive review, and I believe we should not remove these rules. If we extend the rules with the lead time then we should additionally give _all_ assigned reviewers time to react. Besides that, I think it should be the author who is responsible for merging the request, following the rules.

**Comment by nhoriguchi** [comment]
> **Whom to request review from?** So far the pace of contribution looks moderate, and all maintainers seem to care about most of the changes. Nevertheless, we could make it a bit more convenient and [set up code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners), even if it would be as simple as making all maintainers default owners for everything in the repo.

OK, so let's try code owner feature.  I think that another reason to use some automated mechanism to assign reviewers is to avoid misoperations. I usually set reviewers by choosing all maintainers from the account list shown by clicking the gear icon on the right of "Reviewers" section in web UI. The list shows many unrelated accounts, so I likely to click them (leading to send wrong notifications.) Maybe it's safer to avoid this operation.

> It could also make sense to expect former contributors to the modified code making more thorough review.

Yes, that's right. Linux Kernel project (as a reference) provides their [own tool to find reviewers](https://github.com/torvalds/linux/blob/master/scripts/get_maintainer.pl). Maybe we can do something similar easily with `git-diff` and `git-blame`, but it seems that GitHub recently purchased [Pull Panda](https://pullpanda.com/assigner?ref=githubapp) to cover this issue, so that might help us.

> **How long to wait for feedback?** Maybe 24 hours is a bit short notice. I would suggest to give the assigned reviewers a couple of working days for giving their feedback or explicitly asking for more time. In the latter case, the author might remind the delayed reviewer after a week and give another week.

Yes, the suggested policy looks reasonable, I feel easy to have a clear policy.

> **How to merge?** Currently, each request seems to only require no negative and at least one positive review, and I believe we should not remove these rules. If we extend the rules with the lead time then we should additionally give _all_ assigned reviewers time to react. Besides that, I think it should be the author who is responsible for merging the request, following the rules.

That might not work when the author is not a maintainer, so I think that the first reviewer (approver) can take the responsibility for merge operation.

**Comment by ynamiki** [comment]
@sergefdrv @Naoya-Horiguchi Thanks for your suggestion. Let me summarize previous comments. Please point out any errors.

- Create [a CODEOWNERS file](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners). At this moment, we set @sergefdrv @Naoya-Horiguchi @ynamiki) as owners of all files.

Code reviewing polices:

- [Add] A pull request will be set reviewers automatically according to the CODEOWNERS file.
- [No change] A pull request requires no negative and at least one positive review from the reviewers.
- [Add] The reviewers give their feedback or explicitly ask for more time in a couple of working days. In the latter case, the author might remind the delayed reviewer after a week and give another week.
- [Add, discussion needed] If the author of the request is a maintainer, he/she is responsible for merging the request, following the rules. Otherwise, the first reviewer takes the responsibility.

For the last item, I merged two suggestions and I think we can try with this.

I think it is good to document the policies. Is it reasonable choice for us to add some descriptions to [CONTRIBUTING.md](https://github.com/hyperledger-labs/minbft/blob/master/CONTRIBUTING.md#merge-rules)?

If I get your approvals, I will create a CODEOWNDERS file and the document.

**Comment by sergefdrv** [comment]
@ynamiki Thank you for summarizing the conversation. I think it captures well the outcome of our discussion.

> If the author of the request is a maintainer, he/she is responsible for merging the request, following the rules. Otherwise, the first reviewer takes the responsibility.

Maybe we could also agree that one of the reviewers assigns the pull request to themselves and thus becomes responsible for merging? It could be the author in the first case, and the first reviewer otherwise.

**Comment by ynamiki** [comment]
> Maybe we could also agree that one of the reviewers assigns the pull request to themselves and thus becomes responsible for merging?

@sergefdrv Thanks for pointing that out. I'll create a pull request to update the document to include the above policies.

**Comment by sergefdrv** [comment]
As of splitting responsibilities, I would like to overlook all changes, especially the core logic. I might be slightly less engaged in discussing "infrastructural" updates. :slightly_smiling_face:

**Comment by ynamiki** [comment]
I can take care of the infrastructural part (i.e. build system, CI, Docker (TODO), etc.).

**Comment by nhoriguchi** [comment]
So should I cover all except core logic and infrastructure part? I'm OK on it.

**Comment by ynamiki** [comment]
Then, let me think about how we describe a CODEOWNERS file; I will create a PR later.
