### ISSUE TITLE
Check updates to CI Dockerfile

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#59]
Since #50 has been merged, we use a custom docker image in CI, which is maintained on Docker Hub. The image is built from [Dockerfile](https://github.com/hyperledger-labs/minbft/blob/master/.circleci/images/Dockerfile) managed in the source tree. As long as this Dockerfile stays unchanged, it is safe to keep using the same image from Docker Hub when running CI checks. 

However, we would like to update the image from time to time. In that case, we should ensure the update will not break our CI. This comes down to running CI checks on the updated image before changing our default CI image on Docker Hub.

#52 attempts to update the Dockerfile without running CI checks on the updated image. #58 suggests changes to the Dockerfile to always fetch the latest release of `gometalinter` tool, but it's not clear how to trigger image build and ensure if the resulting image does not break CI. https://github.com/hyperledger-labs/minbft/pull/52#issuecomment-448104698 suggests using a separate repository for the Dockerfile.

We need to define a scheme for updating the CI docker image, preferably without risking to suddenly break our CI.

**Comment by nhoriguchi** [comment]
Thanks for summarizing points. I agree that we need a process to confirm that the built custom image is valid before switching. Let me share some ideas about what/how:

- one possible way to do the check is to run CI test process with the new image for the commit which was already confirmed to pass with the old image,
- to do that, we need to define another image tag for the check and tell CI process which tag to use,
- we have two triggering 1) for building new custom image and 2) for running CI process to check the new image. I'm still not sure that Docker Hub / CircleCI provide enough features to meet out requirements.

**Comment by ynamiki** [comment]
I am thinking reverting #50 (i.e. do not use a custom Docker image) is reasonable....

To implement this issue, it might be something like the following:

1. (At creating a PR) Check whether `Dockerfile` was updated.
2. If `Dockerfile` was updated or `gometalinter` was updated, build a new image (not on Docker Hub but CircleCI) (How we keep the version of `gometalinter` used in the current image?)
3. If a new image has been built, tag it with the commit hash and push to Docker Hub.
4. Run the test on the image.
5. If the PR has been merged, tag the new image with `latest`. Otherwise, delete the image from Docker Hub.

Step 1-4 will be coded in [CircleCI configuration](https://github.com/hyperledger-labs/minbft/blob/master/.circleci/config.yml) ([document](https://circleci.com/docs/2.0/building-docker-images/)).
To implement Step 5, catch the event through [GitHub webhooks](https://developer.github.com/webhooks/) and operate Dock Hub (where we run this? [Amazon API Gateway](https://aws.amazon.com/api-gateway/) and [Lambda](https://aws.amazon.com/lambda/)?).

I afraid that this is too complicated.

**Comment by nhoriguchi** [comment]
... (I undo the previous comment because that's not a good comment... sorry) I just wait for feedback from Sergey. Thanks.

**Comment by sergefdrv** [comment]
I looked at the timing of CI stages. My observations:

- "Spin up Environment" takes up ~20s with a custom image; timing with a standard image is similar, sometimes significantly less (even 1s)
- "Install Go": 3-4s
- "Install Intel SGX SDK": 3-10s
- "Install gometalinter": 4-8s

So I think, given little to zero benefit of the custom image, we might be fine reverting #50.

Notice, that before switching to a custom docker image, gometalinter was installed with `go get`, followed by `gometalinter --install`. Downloading and extracting a binary should be faster.

Interestingly, Travis CI [documentation](https://docs.travis-ci.com/user/caching/#things-not-to-cache) mentions:

> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source

This is about caching, but I guess the idea would roughly apply to our case, as well.

**Comment by ynamiki** [comment]
@sergefdrv Thanks for your survey.

I would like to propose to stop using a custom Docker image. Using a custom image was aimed to improve efficiency of the build process, but the time reduced is less than 30 seconds and it brings the issue described in the first comment. The issue is not intractable, but need a lot of efforts to implement. I think it is reasonable to go back to the previous, simple way; a little longer build time is ignoble. 

@sergefdrv @Naoya-Horiguchi If I obtain approval from you, I will create a PR for this.

**Comment by sergefdrv** [comment]
@ynamiki Please go ahead

**Comment by nhoriguchi** [comment]
@ynamiki I'm OK for reverting.
