### ISSUE TITLE
settle explicit dependency on GOPATH

### ISSUE THREAD

**Issue by nhoriguchi** [hyperledger-labs/minbft#86]
minbft is now treated as Go module with #82. Go module is free from GOPATH generally, but we still have dependency on it. Removing GOPATH is not mandatory or urgent but will be done at some point.

**Comment by ynamiki** [comment]
`keytool` and `peer` commands have (optional) dependency on `$GOPATH`; they try to find `$GOPATH/src/github.com/hyperledger-labs/minbft/usig/sgx/enclave/libusig.signed.so` by default (we can override the default by a command-line option or a configuration file). Now we are a Go module then a user don't need to place the directory in GOPATH. And even a user place it in GOPATH, he/she may not define the `$GOPATH`; it is optional since Go 1.8.

So, we would better to rethink the default. There may be some options:

1. `./libusig.signed.so` and copy the library to `sample/bin` in the build process: A user can try our example with zero configuration wherever he/she place the project directory.
2. `GOPATH/src/github.com/hyperledger-labs/minbft/usig/sgx/enclave/libusig.signed.so`, `GOPATH` is expand by [`build.Default.GOPATH`](https://golang.org/pkg/go/build/#Context): By this, if `$GOPATH` is not defined, the default path (`$HOME/go`) is used so we are independent from `$GOPATH`. However, a user needs to specify path when he/she try our example placing the project directory outside GOPATH.

@sergefdrv @Naoya-Horiguchi I would like to get your thought.

**Comment by nhoriguchi** [comment]
Hi @ynamiki, I like option 1. And `sample/bin` looks a good place for `libusig.signed.so`.

**Comment by ynamiki** [comment]
I should add some description for the option 1:
This means the commands find the library in the same directory (we can get a path of an executable by [os.Executable()](https://tip.golang.org/pkg/os/#Executable)). So this is works wherever a current directory is.

**Comment by sergefdrv** [comment]
I prefer the option 1 but would also consider a slight variation of it: installing the enclave binary in `sample` directory. Then the sample configuration files can refer to it using a relative path, i.e. just using the file name. Specifying a relative path respective to the base directory of executable might look a bit unconventional/confusing in a configuration file.

**Comment by sergefdrv** [comment]
However, using `sample/bin` as a destination to install the enclave binary actually looks pretty good. Another alternative might be `sample/lib`.

**Comment by sergefdrv** [comment]
BTW, how about adding `install` target to our makefiles? This target can handle both installation of CLI binaries (`peer` and `keytool`) and the enclave binary/library. We can set `prefix=$(srcdir)/sample` by default until the project is mature enough to change it to the conventional `/usr/local/`.
